package com.espe.salud.mapper.paciente;

import com.espe.salud.domain.entities.paciente.Paciente;
import com.espe.salud.dto.paciente.PacienteBannerDTO;
import com.espe.salud.dto.paciente.PacienteDTO;
import com.espe.salud.dto.paciente.PacienteExternoDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring", uses = {ContactoMapper.class, ContactoEmergenciaMapper.class})
public interface PacienteMapper {

    @Mapping(source = "codigo", target = "id")
    @Mapping(source = "persona.apellidoPaterno", target = "apellidoPaterno")
    @Mapping(source = "persona.apellidoMaterno", target = "apellidoMaterno")
    @Mapping(source = "persona.primerNombre", target = "primerNombre")
    @Mapping(source = "persona.segundoNombre", target = "segundoNombre")
    @Mapping(source = "persona.cedula", target = "cedula")
    @Mapping(source = "persona.fechaNacimiento", target = "fechaNacimiento")
    @Mapping(source = "persona.sexo", target = "sexo")
    @Mapping(source = "persona.estadoCivil", target = "estadoCivil")
    @Mapping(source = "persona.religion", target = "religion")
    @Mapping(source = "persona.aceptaTransfucion", target = "aceptaTransfucion")
    @Mapping(source = "persona.grupoSanguineo", target = "grupoSanguineo")
    @Mapping(source = "persona.lateralidad", target = "lateralidad")
    @Mapping(source = "persona.instruccion", target = "instruccion")
    @Mapping(source = "persona.profesion", target = "profesion")
    @Mapping(source = "persona.vinculadoEspe", target = "vinculadoEspe")
    @Mapping(source = "persona.pueblos", target = "pueblos")
    @Mapping(source = "persona.grupoCultural", target = "grupoCultural")
    @Mapping(source = "persona.seguroSalud", target = "seguroSalud")
    @Mapping(source = "persona.asociacionAfiliada", target = "asociacionAfiliada")
    @Mapping(source = "persona.ciuo", target = "ciuo")
    @Mapping(source = "persona.idConsultorio", target = "idDispensario")
    @Mapping(source = "persona.paisNacimiento", target = "paisNacimiento")
    @Mapping(source = "persona.provinciaNacimiento", target = "provinciaNacimiento")
    @Mapping(source = "persona.cantonNacimiento", target = "cantonNacimiento")
    @Mapping(source = "persona.nacionalidad", target = "nacionalidad")
    @Mapping(source = "persona.nacionalidad2", target = "nacionalidad2")
    @Mapping(source = "persona.contacto", target = "contacto")
    @Mapping(source = "persona.contactosEmergencia", target = "contactosEmergencia")
    PacienteDTO toPacienteDTO(Paciente paciente);

//    @Mapping(source = "apellidoPaterno", target = "persona.apellidoPaterno")
//    @Mapping(source = "apellidoMaterno", target = "persona.apellidoMaterno")
//    @Mapping(source = "primerNombre", target = "persona.primerNombre")
//    @Mapping(source = "segundoNombre", target = "persona.segundoNombre")
//    @Mapping(source = "cedula", target = "persona.cedula")
//    @Mapping(source = "fechaNacimiento", target = "persona.fechaNacimiento")
//    @Mapping(source = "sexo", target = "persona.sexo")
//    @Mapping(source = "estadoCivil", target = "persona.estadoCivil")
//    @Mapping(source = "religion", target = "persona.religion")
//    @Mapping(source = "aceptaTransfucion", target = "persona.aceptaTransfucion")
//    @Mapping(source = "grupoSanguineo", target = "persona.grupoSanguineo")
//    @Mapping(source = "lateralidad", target = "persona.lateralidad")
//    @Mapping(source = "instruccion", target = "persona.instruccion")
//    @Mapping(source = "profesion", target = "persona.profesion")
//    @Mapping(source = "vinculadoEspe", target = "persona.vinculadoEspe")
//    @Mapping(source = "pueblos", target = "persona.pueblos")
//    @Mapping(source = "grupoCultural", target = "persona.grupoCultural")
//    @Mapping(source = "seguroSalud", target = "persona.seguroSalud")
//    @Mapping(source = "asociacionAfiliada", target = "persona.asociacionAfiliada")
//    @Mapping(source = "ciuo", target = "persona.ciuo")
//    @Mapping(source = "idDispensario", target = "persona.idConsultorio")
//    @Mapping(source = "paisNacimiento", target = "persona.paisNacimiento")
//    @Mapping(source = "provinciaNacimiento", target = "persona.provinciaNacimiento")
//    @Mapping(source = "cantonNacimiento", target = "persona.cantonNacimiento")
//    @Mapping(source = "nacionalidad", target = "persona.nacionalidad")
//    @Mapping(source = "nacionalidad2", target = "persona.nacionalidad2")
//    @Mapping(source = "contacto", target = "persona.contacto")
//    @Mapping(source = "contactosEmergencia", target = "persona.contactosEmergencia")
//    Paciente toPaciente(PacienteDTO pacienteDTOa);

    List<PacienteDTO> toPacientesDTO(List<Paciente> pacientes);

    Paciente fromPacienteBannerDTOToPaciente(PacienteBannerDTO pacienteBannerDTO);

    @Mapping(source = "apellidoPaterno", target = "persona.apellidoPaterno")
    @Mapping(source = "apellidoMaterno", target = "persona.apellidoMaterno")
    @Mapping(source = "primerNombre", target = "persona.primerNombre")
    @Mapping(source = "segundoNombre", target = "persona.segundoNombre")
    @Mapping(source = "cedula", target = "persona.cedula")
    @Mapping(source = "fechaNacimiento", target = "persona.fechaNacimiento")
    @Mapping(source = "sexo", target = "persona.sexo")
    @Mapping(source = "estadoCivil", target = "persona.estadoCivil")
    @Mapping(source = "religion", target = "persona.religion")
    @Mapping(source = "aceptaTransfucion", target = "persona.aceptaTransfucion")
    @Mapping(source = "grupoSanguineo", target = "persona.grupoSanguineo")
    @Mapping(source = "lateralidad", target = "persona.lateralidad")
    @Mapping(source = "instruccion", target = "persona.instruccion")
    @Mapping(source = "profesion", target = "persona.profesion")
    @Mapping(source = "vinculadoEspe", target = "persona.vinculadoEspe")
    @Mapping(source = "pueblos", target = "persona.pueblos")
    @Mapping(source = "grupoCultural", target = "persona.grupoCultural")
    @Mapping(source = "seguroSalud", target = "persona.seguroSalud")
    @Mapping(source = "asociacionAfiliada", target = "persona.asociacionAfiliada")
    @Mapping(source = "ciuo", target = "persona.ciuo")
    @Mapping(source = "idDispensario", target = "persona.idConsultorio")
    @Mapping(source = "paisNacimiento", target = "persona.paisNacimiento")
    @Mapping(source = "provinciaNacimiento", target = "persona.provinciaNacimiento")
    @Mapping(source = "cantonNacimiento", target = "persona.cantonNacimiento")
    @Mapping(source = "nacionalidad", target = "persona.nacionalidad")
    @Mapping(source = "nacionalidad2", target = "persona.nacionalidad2")
    @Mapping(source = "contacto", target = "persona.contacto")
    @Mapping(source = "contactosEmergencia", target = "persona.contactosEmergencia")
    Paciente fromPacienteExternoDTOToPaciente(PacienteExternoDTO pacienteExternoDTO);


//    @Mapping(source = "apellidoPaterno", target = "persona.apellidoPaterno")
//    @Mapping(source = "apellidoMaterno", target = "persona.apellidoMaterno")
//    @Mapping(source = "primerNombre", target = "persona.primerNombre")
//    @Mapping(source = "segundoNombre", target = "persona.segundoNombre")
//    @Mapping(source = "cedula", target = "persona.cedula")
//    @Mapping(source = "fechaNacimiento", target = "persona.fechaNacimiento")
//    @Mapping(source = "sexo", target = "persona.sexo")
//    @Mapping(source = "estadoCivil", target = "persona.estadoCivil")
//    @Mapping(source = "religion", target = "persona.religion")
//    @Mapping(source = "aceptaTransfucion", target = "persona.aceptaTransfucion")
//    @Mapping(source = "grupoSanguineo", target = "persona.grupoSanguineo")
//    @Mapping(source = "lateralidad", target = "persona.lateralidad")
//    @Mapping(source = "instruccion", target = "persona.instruccion")
//    @Mapping(source = "profesion", target = "persona.profesion")
//    @Mapping(source = "vinculadoEspe", target = "persona.vinculadoEspe")
//    @Mapping(source = "pueblos", target = "persona.pueblos")
//    @Mapping(source = "grupoCultural", target = "persona.grupoCultural")
//    @Mapping(source = "seguroSalud", target = "persona.seguroSalud")
//    @Mapping(source = "asociacionAfiliada", target = "persona.asociacionAfiliada")
//    @Mapping(source = "ciuo", target = "persona.ciuo")
//    @Mapping(source = "idDispensario", target = "persona.idConsultorio")
//    @Mapping(source = "paisNacimiento", target = "persona.paisNacimiento")
//    @Mapping(source = "provinciaNacimiento", target = "persona.provinciaNacimiento")
//    @Mapping(source = "cantonNacimiento", target = "persona.cantonNacimiento")
//    @Mapping(source = "nacionalidad", target = "persona.nacionalidad")
//    @Mapping(source = "nacionalidad2", target = "persona.nacionalidad2")
//    @Mapping(source = "contacto", target = "persona.contacto")
//    @Mapping(source = "contactosEmergencia", target = "persona.contactosEmergencia")
//    PacienteDTO fromPacienteExternoToPacienteDTO(Paciente paciente);
}