-- /*USUARIOS */
INSERT INTO MZSTUSU(MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_CEDULA, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (369981, 'PILLAGA ZHAGÑAY, LUIS ANTONIO', '0301971495', TRUE, 1, 1)
INSERT INTO MZSTUSU(MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_CEDULA, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (369895, 'LOPEZ GUERRON, JHOJAN ALEJANDRO', '0401749817', TRUE, 2, 2)
INSERT INTO MZSTUSU(MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_CEDULA, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (51265, 'MAIGUALCA TOAPANTA, DIEGO ANDRES', '0550362891', TRUE, 3, 2)
INSERT INTO MZSTUSU(MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_CEDULA, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (62455, 'CABRERA CORDOVA, ANTHONY ROLANDO', '1718104027', TRUE, 1, 2)
INSERT INTO MZSTUSU(MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_CEDULA, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (78540, 'LLAMUCA CARRERA, BOLIVAR ERNESTO', '1803944451', TRUE, 1, 1)


--/* PACIENTE */
INSERT INTO MZSTPAC(MZSTPAC_NUMERO_ARCHIVO, MZSTPAC_NOMBRE_COMPLETO, MZSTPAC_ES_EMPLEADO, MZSTPAC_ES_ESTUDIANTE, MZSTPAC_ACEPTA_TRANSFUCION, MZSTPAC_LATERALIDAD, MZSTPAC_TIPO_PACIENTE, FK_CDIS_PAC) VALUES ('0301971495', 'LUIS ANTONIO PILLAGA ZHAGÑAY', false, true, true, 'DIESTRO', 'INTERNO', 1)

--/* ANTECEDENTE LABORAL */
INSERT INTO MZSTANTLAB(FK_PAC_ANTLAB, FK_USU_ANTLAB) VALUES ('1', '369981')

--/* ANTECEDENTE ACCIDENTE TRABAJO */
INSERT INTO MZSTANTACCTRA(MZSTANTTRA_EMPRESA,MZSTANTTRA_FECHA,MZSTANTTRA_OBSERVACIONES,MZSTANTTRA_RECIBIO_ATENCION,MZSTANTTRA_RIESGO_IMPLICADO,MZSTANTTRA_SECUELAS,MZSTANTTRA_HORAS_REPOSO,MZSTDETANT_LUGAR_ATENCION,MZSTDETANT_NATURALEZA,MZSTDETANT_PARTE_CUERPO_AFECTADA,FK_ANTLAB_ANTACCTRA) VALUES ('ELEPCO S.A.','23-02-2021','EL SEÑOR LUIS PILLAGA SE DESEMPEÑABA EN TAREAS ARDUAS, SUBIDO EN POSTES DE LUZ Y CARGANDO MATERIAL PESADO.',true,'SE LE ENYESÓ LA ESPALDA MIENTRAS DURA LA LESIÓN','PADECE ESCOLIOSIS',30.0,'CENTRO DE SALUD TIPO D BIBLIÁN','HEMORRAGIA','PARTE ALTA LUMBAR',1)

--/* ANTECEDENTE INCIDENTE TRABAJO */
INSERT INTO MZSTANTINCTRA(MZSTANTTRA_EMPRESA,MZSTANTTRA_FECHA,MZSTANTTRA_OBSERVACIONES,MZSTANTTRA_RECIBIO_ATENCION,MZSTANTTRA_RIESGO_IMPLICADO,MZSTANTTRA_SECUELAS,MZSTANTTRA_HORAS_REPOSO,MZSTDETANT_LUGAR_ATENCION,MZSTDETANT_NATURALEZA,MZSTDETANT_PARTE_CUERPO_AFECTADA,FK_ANTLAB_ANTINCTRA) VALUES ('ELEPCO S.A.','23-02-2021','EL TIEMPO DE DESCANSO SOLICITADO ES CORTO',true,'PERDIDA DE LA MOTRICIDAD EN EL TENDÓN DEL CODO','INCAPACIDAD PARA GIRAR EL CODO CON NORMALIDAD',30.0,'IESS AZOGUES','HEMATOMA','CODO IZQUIERDO',1)

--/* ANTECEDENTE ENFERMEDAD PROFESIONAL */
INSERT INTO MZSTANTENFPRO(MZSTANTTRA_EMPRESA,MZSTANTTRA_FECHA,MZSTANTTRA_OBSERVACIONES,MZSTANTTRA_RECIBIO_ATENCION,MZSTANTTRA_RIESGO_IMPLICADO,MZSTANTTRA_SECUELAS,MZSTANTTRA_HORAS_REPOSO,MZSTANTENFPRO_DIAGNOSTICO, FK_ANTLAB_ANTENFPRO) VALUES ('ELEPCO S.A.','01-01-2010','EL DAÑO PULMONAR SERÁ PERMANENTE',true,'INCAPACIDAD PARA REALIZAR TRABAJO FÍSICO','SE LE HAN ASIGNADO TAREAS DE OFICINA',72.0,'FIBROSIS PULMONAR CAUSADA POR LA PERMANENTE INHALACIÓN DE GASES PESADOS',1)

--/* FACTOR RIESGO PUESTO ACTUAL */
INSERT INTO MZSTFACRIEPUEACT(MZSTFACRIEPUEACT_PUESTO_TRABAJO,MZSTFACRIEPUEACT_ACTIVIDAD_PUESTO,MZSTFACRIEPUEACT_MEDIDA_PREVENTIVA,MZSTFACRIEPUEACT_MAQUINARIA,FK_ANTLAB_FACRIEPUEACT) VALUES ('UNVIERSIDAD DE LAS FUERZAS ARMADAS ESPE SEDE LATACUNGA','DOCENTE','ACTIVIDADES DE DOCENCIA E INVESTIGACIÓN','USO DE EQUIPOS DE COMPUTACIÓN CONECTADOS A INTERNET',1)

---/* FACTOR RIESGO PUESTO ACTUAL - RIESGOS FÍSICOS */
INSERT INTO MZSTREL_RIEFIS_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEFIS) VALUES (1,1)
INSERT INTO MZSTREL_RIEFIS_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEFIS) VALUES (1,2)

---/* FACTOR RIESGO PUESTO ACTUAL - RIESGOS QUÍMICOS */
INSERT INTO MZSTREL_RIEQUI_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEQUI) VALUES (1,1)
INSERT INTO MZSTREL_RIEQUI_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEQUI) VALUES (1,2)

---/* FACTOR RIESGO PUESTO ACTUAL - RIESGOS MECÁNICOS */
INSERT INTO MZSTREL_RIEMEC_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEMEC) VALUES (1,1)
INSERT INTO MZSTREL_RIEMEC_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEMEC) VALUES (1,2)

---/* FACTOR RIESGO PUESTO ACTUAL - RIESGOS ERGONÓMICOS */
INSERT INTO MZSTREL_RIEERG_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEERG) VALUES (1,1)
INSERT INTO MZSTREL_RIEERG_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEERG) VALUES (1,2)

---/* FACTOR RIESGO PUESTO ACTUAL - RIESGOS BIOLÓGICOS */
INSERT INTO MZSTREL_RIEBIO_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEBIO) VALUES (1,1)
INSERT INTO MZSTREL_RIEBIO_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEBIO) VALUES (1,2)

---/* FACTOR RIESGO PUESTO ACTUAL - RIESGOS PSICOLÓGICOS */
INSERT INTO MZSTREL_RIEPSI_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEPSI) VALUES (1,1)
INSERT INTO MZSTREL_RIEPSI_FACRIEPUEACT(FK_FACRIEPUEACT, FK_RIEPSI) VALUES (1,2)

--/* ACTIVIDAD EXTRALABORAL */
INSERT INTO MZSTACTEXT(MZSTDETTRA_EMPRESA,MZSTDETTRA_PUESTO_TRABAJO,MZSTDETTRA_ACTIVIDAD,MZSTDETTRA_MESES,MZSTDETTRA_USABAN_SEGURIDAD,MZSTDETTRA_VIGILANCIA_SALUD,MZSTDETTRA_OBSERVACION,MZSTDETTRA_RIESGO,FK_ANTLAB_ACTEXT) VALUES ('HELADERÍA "CRISTY"','VENDEDOR A MEDIO TIEMPO','VENTA DE HELADOS POR LAS NOCHES',48.0,false,true,'UTILIZA LA MÁQUINA PREPARADORA Y MEZCLADORA DE HELADO','FISICO', 1)

--/* ANTECEDENTE EMPLEO ANTERIOR */
INSERT INTO MZSTANTEMPANT(MZSTDETTRA_EMPRESA,MZSTDETTRA_PUESTO_TRABAJO,MZSTDETTRA_ACTIVIDAD,MZSTDETTRA_MESES,MZSTDETTRA_USABAN_SEGURIDAD,MZSTDETTRA_VIGILANCIA_SALUD,MZSTDETTRA_OBSERVACION,MZSTDETTRA_RIESGO,FK_ANTLAB_ANTEMPANT) VALUES ('DIARIO EL MERCURIO','REDACCIÓN','REDACTOR EDITORIAL',6,false,true,'REDACCIÓN EN COMPUTADORA', 'PSICOSOCIAL', 1)

