-- /*PARENTESCO */

INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Padre', 'CONSANGUINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Madre', 'CONSANGUINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Hijo/a', 'CONSANGUINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Abuelo/a materna', 'CONSANGUINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Abuelo/a paterno', 'CONSANGUINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Tío/a materna', 'CONSANGUINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Tío/a paterno', 'CONSANGUINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Conyugue', 'AFINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Amigo/a', 'AFINIDAD');
INSERT INTO MZSTPAR(MZSTPAR_NOMBRE, MZSTPAR_TIPO) VALUES('Otro', 'CONSANGUINIDAD');
