-- /*PARENTESCO */
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Padre', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Madre', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Hijo/a', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Abuelo/a materna', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Abuelo/a paterno', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Tío/a materna', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Tío/a paterno', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Conyugue', 'AFINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Amigo/a', 'AFINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Otro', 'CONSANGUINIDAD');


-- /*AREAS SALUD */
INSERT INTO MZSTCARESAL (MZSTCARESAL_NOMBRE) VALUES ('Medicina General');
INSERT INTO MZSTCARESAL (MZSTCARESAL_NOMBRE) VALUES ('Medicina Ocupacional');
INSERT INTO MZSTCARESAL (MZSTCARESAL_NOMBRE) VALUES ('Enfermeria');
INSERT INTO MZSTCARESAL (MZSTCARESAL_NOMBRE) VALUES ('Odontología');

-- /*DISPENSARIOS */
INSERT INTO MZSTCDIS(MZSTCDIS_INSTITUCION_SISTEMA, MZSTCDIS_UNIDAD_OPERATIVA, MZSTCDIS_UNI_CODIGO) VALUES('Universidad de las Fuerzas Armadas ESPE','Belisario Quevedo', 'COD122312');
INSERT INTO MZSTCDIS(MZSTCDIS_INSTITUCION_SISTEMA, MZSTCDIS_UNIDAD_OPERATIVA, MZSTCDIS_UNI_CODIGO) VALUES('Universidad de las Fuerzas Armadas ESPE','Latacunga Centro', 'COD123312');

-- /*USUARIOS */
INSERT INTO MZSTUSU (MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (369981, 'PILLAGA ZHAGÑAY, LUIS ANTONIO', TRUE, 1, 1)
INSERT INTO MZSTUSU (MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (369895, 'LOPEZ GUERRON, JHOJAN ALEJANDRO', TRUE, 2, 2)
INSERT INTO MZSTUSU (MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (51265, 'MAIGUALCA TOAPANTA, DIEGO ANDRES', TRUE, 3, 2)
INSERT INTO MZSTUSU (MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (62455, 'CABRERA CORDOVA, ANTHONY ROLANDO', TRUE, 1, 2)
INSERT INTO MZSTUSU (MZSTUSU_PIDM, MZSTUSU_NOMBRES, MZSTUSU_ACTIVO, FK_ARESAL_USU, FK_CDIS_USU) VALUES (78540, 'LLAMUCA CARRERA, BOLIVAR ERNESTO', TRUE, 1, 1)