-- /*PARENTESCO */

INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Padre', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Madre', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Hijo/a', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Abuelo/a materna', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Abuelo/a paterno', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Tío/a materna', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Tío/a paterno', 'CONSANGUINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Conyugue', 'AFINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Amigo/a', 'AFINIDAD');
INSERT INTO MZSTCPAR(MZSTCPAR_NOMBRE, MZSTCPAR_TIPO) VALUES('Otro', 'CONSANGUINIDAD');

/*ASOSIACIONES*/
INSERT INTO MZSTCASO(MZSTCASO_NOMBRE) VALUES('Ninguna');
INSERT INTO MZSTCASO(MZSTCASO_NOMBRE) VALUES('Asociacion de servidores públicos');
INSERT INTO MZSTCASO(MZSTCASO_NOMBRE) VALUES('Asociacion de docentes');
INSERT INTO MZSTCASO(MZSTCASO_NOMBRE) VALUES('Asociacion 5 de julio');

/*SEGURO SALUD*/
INSERT INTO MZSTCSEGSAL(MZSTCSEGSAL_NOMBRE) VALUES('No aporta');
INSERT INTO MZSTCSEGSAL(MZSTCSEGSAL_NOMBRE) VALUES('Seguro privado');
INSERT INTO MZSTCSEGSAL(MZSTCSEGSAL_NOMBRE) VALUES('Jubilado del IESS/SSC/ISSFA/ISSPOL');
INSERT INTO MZSTCSEGSAL(MZSTCSEGSAL_NOMBRE) VALUES('IESS-Seguro campesino');
INSERT INTO MZSTCSEGSAL(MZSTCSEGSAL_NOMBRE) VALUES('IESS-Seguro voluntario');
INSERT INTO MZSTCSEGSAL(MZSTCSEGSAL_NOMBRE) VALUES('IESS-Seguro general');
INSERT INTO MZSTCSEGSAL(MZSTCSEGSAL_NOMBRE) VALUES('IESS-ISSPOL');
INSERT INTO MZSTCSEGSAL(MZSTCSEGSAL_NOMBRE) VALUES('IESS-ISSFA');

-- /* TIPOS DE CERTIFICADO */
INSERT INTO MZSTCTIPCER(MZSTCTIPCER_NOMBRE) VALUES('CERTIFICADO1');
INSERT INTO MZSTCTIPCER(MZSTCTIPCER_NOMBRE) VALUES('CERTIFICADO2');
INSERT INTO MZSTCTIPCER(MZSTCTIPCER_NOMBRE) VALUES('CERTIFICADO3');